version: '3.9'

services:
  queries_challenge:
    image: postgres
    container_name: queries_challenge
    restart: always
    ports:
      - 5432:5432
      - 9229-9229
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=orm
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: orm
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - queries_challenge
    depends_on:
      - queries_challenge

volumes:
  pgdata:
    driver: local